// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmxjfdmknrpvfivpmcou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRteGpmZG1rbnJwdmZpdnBtY291Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTgxMDMsImV4cCI6MjA2NTU3NDEwM30.TPqaG5_2FVBX2-7TiIU6jMBSLC2ASdwWQQucLfQnkTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);